# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master
  - AsyncClient

pool:
  vmImage: "windows-latest"

variables:
  solution: "./Tweetinvi.NETCore.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

steps:
  - task: NuGetToolInstaller@1
    displayName: Installing nuget

  - task: NuGetCommand@2
    displayName: dotnet restore
    inputs:
      restoreSolution: "$(solution)"

  - task: DotNetCoreCLI@2
    displayName: Build solution
    inputs:
      command: "build"
      projects: "$(solution)"

  - task: DotNetCoreCLI@2
    displayName: Run Tests
    inputs:
      command: test
      arguments: $(solution) /p:CollectCoverage=true /p:CoverletOutputFormat="cobertura" /p:CoverletOutput=../lcov

  - task: PublishCodeCoverageResults@1
    displayName: "Publish code coverage"
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(Build.SourcesDirectory)/Tests/lcov.cobertura.xml

  - task: ResharperCli@2
    continueOnError: true
    inputs:
      solutionOrProjectPath: "$(solution)"
      additionalArguments: "--disable-settings-layers=SolutionPersonal --properties:Configuration=$(buildConfiguration) --profile=$(solution).DotSettings --project=Tweetinvi --project=Tweetinvi.Controllers --project=Tweetinvi.Core --project=Tweetinvi.Credentials --project=Tweetinvi.Logic --project=Tweetinvi.Streams --project=Tweetinvi.AspNet --project=Tweetinvi.WebLogic"
